In [6]:
import numpy as np

a = np.array([1,2,3,4,5])
print(a)
print(type(a))

[2, 3, 4, 5, 6]
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [9]:
import numpy as np

arr_1 = np.array([95,96,97,98,99])
arr_2 = np.array([5,4,3,2,1])
print(arr_1 + arr_2)
print(arr_1 - arr_2)
print(arr_1 * arr_2)
print(arr_1 / arr_2)

[100 100 100 100 100]
[90 92 94 96 98]
[475 384 291 196  99]
[19.         24.         32.33333333 49.         99.        ]


In [13]:
import numpy as np

a = np.array([1,2,3,4,5])
print(np.sum(a))
print(np.mean(a)) # Average
print(np.max(a))
print(np.min(a))
print(np.sqrt(a))

15
3.0
5
1
[1.         1.41421356 1.73205081 2.         2.23606798]


In [17]:
arr_1 = np.array([[1,2,3],[4,5,6]])
print(arr_1)
print(arr_1.shape)
print(arr_1.size)
print(arr_1.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
6
2


In [23]:
import numpy as np

my_arr = np.array([
    [[1,2],[4,5],[6,7]],
    [[7,8],[10,11],[12,13]],
    [[1,2],[4,5],[6,7]]
])

print(my_arr)
print(my_arr.shape)
print(my_arr.size)
print(my_arr.ndim)

[[[ 1  2]
  [ 4  5]
  [ 6  7]]

 [[ 7  8]
  [10 11]
  [12 13]]

 [[ 1  2]
  [ 4  5]
  [ 6  7]]]
(3, 3, 2)
18
3


In [24]:
arr_1 = np.array([[10,20,30],[400,500,600]])
print(arr_1[1,2])

600


In [28]:
arr = np.array([
    [[1,2],[5,7],[9,8]],
    [[3,4],[6,8],[10,12]],
    [[11,13],[14,16],[18,20]]
])

print(arr[2,1,0])
print(arr[1,0,0])
print(arr[-1,-2,-2])
print(arr[-2,-3,-2])

14
3
14
3


In [37]:
import numpy as np

arr = np.array([10,20,8,40,50])
condition = arr>15
# print(condition)
# print(arr[condition])
print(arr[arr>15])

[20 40 50]


Q1. Extract all elements that are
   1. Grater than 10 or less than 5
   2. And not equal to 15

In [43]:
import numpy as np

arr = np.array([
    [12,5,7,20],
    [3,15,8,2],
    [10,25,6,18],
    [4,11,30,9]
])

print(arr[((arr > 10) | (arr < 5)) & (arr != 15)])

[12 20  3  2 25 18  4 11 30]


In [44]:
import numpy as np

arr = np.zeros((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [45]:
import numpy as np

arr = np.full((3,4),7)
print(arr)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [46]:
import numpy as np
arr = np.empty((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [54]:
import pandas as pd

data = {
    "Name": ["John", "Tom", "Joy", "Lee"],
    "Age": [20, 25, 50, 30],
}

df = pd.DataFrame(data)
print(df)
print(type(df))
#print(df.loc[2])
#print(df.loc[2,'Age'])
print(df.iloc[3,0]) # index based

   Name  Age
0  John   20
1   Tom   25
2   Joy   50
3   Lee   30
<class 'pandas.core.frame.DataFrame'>
Lee


In [71]:
import pandas as pd

data = {
    "calories": [420, 390, 380],
    "duration": [50, 40, 45]
}

df = pd.DataFrame(data, index=['day1', 'day2', 'day3'])
#print(df)

print(df.loc['day1'])
print()
print(df.loc[['day1', 'day3']])
print()
print(df['calories'])
print()
print(df.shape)
print()
print(df.size)
print()
print(df.values)
print(type(df.values))

calories    420
duration     50
Name: day1, dtype: int64

      calories  duration
day1       420        50
day3       380        45

day1    420
day2    390
day3    380
Name: calories, dtype: int64

(3, 2)

6

[[420  50]
 [390  40]
 [380  45]]
<class 'numpy.ndarray'>


In [105]:
import pandas as pd
data = {
    "Age": [25, 30, 35, 40, 60],
    "Salary": [50000, 60000, 70000, 80000, 90000]
}

df = pd.DataFrame(data, columns=['Age', 'Salary'])
#print(df.shape[0]) # rows count
#print(len(df)) # rows count (built-in)
#print(df.iloc[-1]) # last index
#print(list(df.columns))
#df["Distance"] = [10, 20, 30, 40, 50]
#df.loc[len(df)] = [28, 55000, 15]
#print(df)
#print(df.sum())
#print(df.mean())
#print(df.describe())
#filtered = df[df['Age']>30]
filtered = df[(df['Age']>28) & (df['Salary']<75000) ]
print(filtered)
print(type(filtered))

   Age  Salary
1   30   60000
2   35   70000
<class 'pandas.core.frame.DataFrame'>


In [158]:
import pandas as pd

df = pd.DataFrame({
    "Product": ["Laptop", "Mouse", "Keyboard", "Monitor", "Headset"],
    "UnitSold": [12, 50, 34, 20, 40],
    "Price": [120000, 1500, 3500, 25000, 6000],
    "Discounts": [0.10, 0.05, 0.08, 0.12, 0.07]
})
print(df)

    Product  UnitSold   Price  Discounts
0    Laptop        12  120000       0.10
1     Mouse        50    1500       0.05
2  Keyboard        34    3500       0.08
3   Monitor        20   25000       0.12
4   Headset        40    6000       0.07


Q1.  1. Calculate the final price after discount for each product
     2. Calculate total revenue for each product
        (for above part 1 and part 2 add both result as new columns to the data frame)
     3. Filter and display only the products where total revenue is grater than 500000
     4. Calculate the total revenue of all products combine

In [134]:
# 01
df["FinalPrice"] = df["Price"] * (1 - df["Discounts"])

# 02
df["TotalRevenue"] = df["FinalPrice"] * df["UnitSold"]
print(df)

# 03
high_revenue = df[df["TotalRevenue"] > 500000]
print()
print(high_revenue)

# 04
total_revenue_all = df["TotalRevenue"].sum()
print()
print(total_revenue_all)

    Product  UnitSold   Price  Discounts  FinalPrice  TotalRevenue
0    Laptop        12  120000       0.10    108000.0     1296000.0
1     Mouse        50    1500       0.05      1425.0       71250.0
2  Keyboard        34    3500       0.08      3220.0      109480.0
3   Monitor        20   25000       0.12     22000.0      440000.0
4   Headset        40    6000       0.07      5580.0      223200.0

  Product  UnitSold   Price  Discounts  FinalPrice  TotalRevenue
0  Laptop        12  120000        0.1    108000.0     1296000.0

2139930.0


In [160]:
new_df = df.drop("Discounts", axis=1)
print(new_df)

    Product  UnitSold   Price
0    Laptop        12  120000
1     Mouse        50    1500
2  Keyboard        34    3500
3   Monitor        20   25000
4   Headset        40    6000


In [164]:
new_df_2 = df.drop(3, axis=0)
print(new_df_2)

    Product  UnitSold   Price  Discounts
0    Laptop        12  120000       0.10
1     Mouse        50    1500       0.05
2  Keyboard        34    3500       0.08
4   Headset        40    6000       0.07


In [178]:
import pandas as pd

df = pd.read_csv("./file_handling/person_data.csv")
print(df)
print(type(df))
print()
df_2 = pd.read_json("./file_handling/details.json")
print(df_2)
print(type(df_2))

   Name  Age    Country      City
0  Alex   16  Sri Lanka   Colombo
1   Mia   17  Australia    Sydney
2  Ravi   15        USA  New York
3  Sara   16         UK    London
4  Liam   17     Canada   Toronto
<class 'pandas.core.frame.DataFrame'>



ValueError: If using all scalar values, you must pass an index