In [6]:
import numpy as np

a = np.array([1,2,3,4,5])
print(a)
print(type(a))

[2, 3, 4, 5, 6]
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [9]:
import numpy as np

arr_1 = np.array([95,96,97,98,99])
arr_2 = np.array([5,4,3,2,1])
print(arr_1 + arr_2)
print(arr_1 - arr_2)
print(arr_1 * arr_2)
print(arr_1 / arr_2)

[100 100 100 100 100]
[90 92 94 96 98]
[475 384 291 196  99]
[19.         24.         32.33333333 49.         99.        ]


In [13]:
import numpy as np

a = np.array([1,2,3,4,5])
print(np.sum(a))
print(np.mean(a)) # Average
print(np.max(a))
print(np.min(a))
print(np.sqrt(a))

15
3.0
5
1
[1.         1.41421356 1.73205081 2.         2.23606798]


In [17]:
arr_1 = np.array([[1,2,3],[4,5,6]])
print(arr_1)
print(arr_1.shape)
print(arr_1.size)
print(arr_1.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
6
2


In [23]:
import numpy as np

my_arr = np.array([
    [[1,2],[4,5],[6,7]],
    [[7,8],[10,11],[12,13]],
    [[1,2],[4,5],[6,7]]
])

print(my_arr)
print(my_arr.shape)
print(my_arr.size)
print(my_arr.ndim)

[[[ 1  2]
  [ 4  5]
  [ 6  7]]

 [[ 7  8]
  [10 11]
  [12 13]]

 [[ 1  2]
  [ 4  5]
  [ 6  7]]]
(3, 3, 2)
18
3


In [24]:
arr_1 = np.array([[10,20,30],[400,500,600]])
print(arr_1[1,2])

600


In [28]:
arr = np.array([
    [[1,2],[5,7],[9,8]],
    [[3,4],[6,8],[10,12]],
    [[11,13],[14,16],[18,20]]
])

print(arr[2,1,0])
print(arr[1,0,0])
print(arr[-1,-2,-2])
print(arr[-2,-3,-2])

14
3
14
3


In [37]:
import numpy as np

arr = np.array([10,20,8,40,50])
condition = arr>15
# print(condition)
# print(arr[condition])
print(arr[arr>15])

[20 40 50]


Q1. Extract all elements that are
   1. Grater than 10 or less than 5
   2. And not equal to 15

In [43]:
import numpy as np

arr = np.array([
    [12,5,7,20],
    [3,15,8,2],
    [10,25,6,18],
    [4,11,30,9]
])

print(arr[((arr > 10) | (arr < 5)) & (arr != 15)])

[12 20  3  2 25 18  4 11 30]
